version: '3.2'
services:

  flask_app:
    container_name: flask-app
    build:
      context: flask_app
    stop_signal: SIGKILL
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${FLASK_PORT}:5000'

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always