---
components:
  CalcRequest:
    type: object
    required:
      - jsonrpc
      - method
      - params
      - id
    properties:
      jsonrpc:
        type: string
        default: 2.0
        pattern: 2.0
      method:
        type: string
        enum:
          - calc.add
          - calc.sub
          - calc.div
          - calc.mul
      params:
        type: object
        properties:
          a:
            type: number
          b:
            type: number
        required:
          - a
          - b
      id:
        type: string
  CalcResponse:
    type: object
    required:
      - jsonrpc
      - id
    properties:
      id:
        type: string
      jsonrpc:
        type: string
        default: 2.0
        pattern: 2.0
      result:
        type: number
      error:
        type: object
        required:
          - code
          - message
          - data
        properties:
          code:
            - type
            - integer
          message:
            - type
            - string
          data:
            - type
            - object
info:
  title: Simple Calculator
  version: 1.0.0
paths:
  "/api":
    post:
      parameters:
      - in: body
        name: Тело запроса
        schema:
          "$ref": "#/components/CalcRequest"
      responses:
        '200':
          description: Математическая операция прошла успешно
          schema:
            "$ref": "#/components/CalcResponse"
        '400':
          description: Bad Request
          schema:
            "$ref": "#/components/CalcResponse"
        '500':
          description: Internal Server Error
          schema:
            "$ref": "#/components/CalcResponse"
      summary: Запрос на математическую операцию
      tags:
      -
swagger: '2.0'
