"""Column from valdis

Revision ID: 7cfad84f1d09
Revises: 897445340c19
Create Date: 2024-01-22 20:13:22.844368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfad84f1d09'
down_revision: Union[str, None] = '897445340c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('col_from_valdis_dev', sa.String(length=50), nullable=True))
    op.drop_column('user', 'col_from_andy_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('col_from_andy_dev', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'col_from_valdis_dev')
    # ### end Alembic commands ###
