"""Column from Andy

Revision ID: 897445340c19
Revises: 
Create Date: 2024-01-22 20:10:30.782983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '897445340c19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('_yoyo_migration')
    op.drop_table('_yoyo_version')
    op.drop_table('yoyo_lock')
    op.drop_table('_yoyo_log')
    op.add_column('user', sa.Column('col_from_andy_dev', sa.String(length=50), nullable=True))
    op.drop_column('user', 'col_from_vlad_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('col_from_vlad_dev', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'col_from_andy_dev')
    op.create_table('_yoyo_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('migration_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('migration_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='_yoyo_log_pkey')
    )
    op.create_table('yoyo_lock',
    sa.Column('locked', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('ctime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('locked', name='yoyo_lock_pkey')
    )
    op.create_table('_yoyo_version',
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('installed_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name='_yoyo_version_pkey')
    )
    op.create_table('_yoyo_migration',
    sa.Column('migration_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('migration_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('applied_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('migration_hash', name='_yoyo_migration_pkey')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    # ### end Alembic commands ###
